### ISSUE TITLE
Support null safety

### ISSUE THREAD

**Issue by mit-mit** [flutterchina/dio#1002]
This is a request to add support for [null safety](https://dart.dev/null-safety) to `package:dio`. This is a very popular package, so would be great to have null safety enabled early. See the [migration guide](https://dart.dev/null-safety/migration-guide) for details about enabling null safety.

### New Issue Checklist

- [x] I have searched for a similar issue in the [project](https://github.com/flutterchina/dio/issues) and found none

**Comment by zepfietje** [comment]
Just wanted to comment, since this is still a relevant issue (not stale).

**Comment by luffyjie** [comment]
Ha Ha! From the Official urge........
From the 2021 greeting! 
 Come on please! my project deep relay on Dio, I also like JOJO serials !!!!!! -:)

**Comment by kuhnroyal** [comment]
Both dependencies `http_parser` and `path` are available as nullsafety versions.

**Comment by pablo-johnson** [comment]
Hello, any update on this?

**Comment by kuhnroyal** [comment]
I have tried to contact @wendux over a month ago via mail but got no response. The last activity in dio was 6 month ago in august.
dio is now the highest blocking package for null safety https://github.com/dart-lang/sdk/wiki/Null-safety-migration-status
Not sure how to proceed, many people need this.

@Sky24n @Insofan Since you are also members of the flutterchina community - do you have any idea if this will be picked up?

**Comment by luffyjie** [comment]
Dear Sir,
    I'm one hundred of percent support dart null-safe, my project use Dio too. But I am not the member of Dio team.
    I search the author of Dio, he is now a staff in BYTE, the creater of TikTok.
    I think maybe someone can stand out make a null-safe branch of Dio.
    Currently I have no time and ability to finish this job.




At 2021-02-12 04:42:48, "Peter Leibiger" <notifications@github.com> wrote:

I have tried to contact @wendux over a month ago via mail but got no response. The last activity in dio was 6 month ago in august.
dio is now the highest blocking package for null safety https://github.com/dart-lang/sdk/wiki/Null-safety-migration-status
Not sure how to proceed, many people need this.

@Sky24n@Insofan Since you are also members of the flutterchina community - do you have any idea if this will be picked up?

**Comment by dmakwt** [comment]
I hope that the Flutter Community @fluttercommunity adapts this package, and update it to support null safety since this package is a very popular package.
@slightfoot @jpnurmi @jeroen-meijer @rapPayne

**Comment by kuhnroyal** [comment]
@luffyjie We already have PR https://github.com/flutterchina/dio/pull/1026 open. I just don't see anyone merging this.

**Comment by miDeb** [comment]
If no mantainer from @flutterchina is active anymore I'd propose that @fluttercommunity forks this package and takes over the mantainance. That's the advantage of open source, right? If the mantainer becomes inactive, creating a fork is the way to go.

Most apps that do networking that is more than just a plain http request (in my case managing cookies, downloading stuff...) probably depend on this library, so it not being null safe very likely blocks many apps from using sound null safety.

**Comment by harsimranmaan** [comment]
yes agreed. I think if no-one responds this week, let's take this over to fluttercommunity. @wendux

**Comment by masseelch** [comment]
For everyone landing here: If you want to use this PR until it gets merged add this to your `pubspec.yaml`:

```yaml
dependency_overrides:
  dio: # https://github.com/flutterchina/dio/issues/1002
    git:
      url: git@github.com:harsimranmaan/dio.git
      ref: null-safety
      path: dio
```

Remove it once it gets merged.

**Comment by IchordeDionysos** [comment]
@wendux any estimation when the version will be published to pub.dev?

You can already publish the version null-safe version to stable.
It will be marked as Preview until the Dart beta version has been published to stable:

https://medium.com/dartlang/preparing-the-dart-and-flutter-ecosystem-for-null-safety-e550ce72c010

**Comment by IchordeDionysos** [comment]
@wendux the package can now be published to stable :)

**Comment by kuhnroyal** [comment]
@wendux Maybe you can pin this issue so others can find it easier.

**Comment by br-programmer** [comment]
when it will be available dio with null safety?

**Comment by yunnywu** [comment]
when it will release a stable version?
