### ISSUE TITLE
Unhandled Exception: Bad state: Stream has already been listened to.

### ISSUE THREAD

**Issue by cikichen** [flutterchina/dio#1007]
E/flutter ( 5180): [ERROR:flutter/lib/ui/ui_dart_state.cc(177)] Unhandled Exception: Bad state: Stream has already been listened to.
E/flutter ( 5180): #0      _StreamController._subscribe (dart:async/stream_controller.dart:710:7)
E/flutter ( 5180): #1      _ControllerStream._createSubscription (dart:async/stream_controller.dart:860:19)
E/flutter ( 5180): #2      _StreamImpl.listen (dart:async/stream_impl.dart:493:9)
E/flutter ( 5180): #3      new _ForwardingStreamSubscription (dart:async/stream_pipe.dart:118:10)
E/flutter ( 5180): #4      _ForwardingStream._createSubscription (dart:async/stream_pipe.dart:88:16)
E/flutter ( 5180): #5      _ForwardingStream.listen (dart:async/stream_pipe.dart:83:12)
E/flutter ( 5180): #6      _HttpIncoming.listen (dart:_http/http_impl.dart:163:8)
E/flutter ( 5180): #7      _HttpClientResponse.listen (dart:_http/http_impl.dart:427:19)
E/flutter ( 5180): #8      new _SinkTransformerStreamSubscription (dart:async/stream_transformers.dart:53:16)
E/flutter ( 5180): #9      _BoundSinkStream.listen (dart:async/stream_transformers.dart:185:9)
E/flutter ( 5180): #10     DioForNative.download (package:dio/src/entry/dio_for_native.dart:156:27)
E/flutter ( 5180): <asynchronous suspension>

`var response = await dio.download(urlPath, savePath,
        cancelToken: cancelToken ?? _cancelToken);`

`dio: ^3.0.10`

**Comment by MuriloRS** [comment]
I have a same issue like this, for me occurs this erro to in the Response.dart file. 
![Sem título](https://user-images.githubusercontent.com/18061819/100886971-350fd900-3493-11eb-9a6b-ce4ee09fa808.png)

**Comment by YvesDelcoigne** [comment]
Same issue here on a POST call, but not for all devices.

Works: Pixel 3, Android 11
Doesn't work: OnePlus A5000, Android 9

**Comment by naiteon** [comment]
I'm commenting here the solution we found for this problem so that anyone facing similar issue can solve it. 
The problem is dart http package does not FULLY support HTTP 1.1. In HTTP 1.1 receiving Transfer-encoding: chunked is permissive whereas it has not been the case in http 1.0. What that means? When you make a http 1.1 request, you may receive data not at once, but in chunks. In that way Content-length will be null, and the http client should concatenate all the chunks and calculate content-length dynamically. And that is what this package was not doing. It would get the header Transfer-encoding: chunked and ignore it, it would obviously be followed by a null Content-length header, raising the ClientException where the content-length would not match the value of the first chucnk 67 does not match 13. 
So the solution was either:  - Add support to http 1.1 (including chunked responses) to this package OR hack it and enforce this client downgrading to http 1.0 (where there is no chunked responses) or ..... Do what we did since we had access to the web server and add a "chunked_transfer_encoding off;" inside the location ~ \.php {   block in  nginx. If you dont use nginx, you probably have a similar option available for your webserver.

**Comment by maxzod** [comment]
any solutions ?

**Comment by naiteon** [comment]
> any solutions ?

https://github.com/flutterchina/dio/issues/1007#issuecomment-738001446

**Comment by maxzod** [comment]
iam using nodejs but i will look for it , thanks

**Comment by jonasbark** [comment]
It happens for us with Dio 4.0 beta 4 and Spring Boot on any PUT or POST request.

It still works fine with Dio 3 so I think it's a regression.

**Comment by deviant-studio** [comment]
dio 4.0 beta 4 works fine for me in flutter android but crashes in the flutter for web

**Comment by maxzod** [comment]
@deviant-studio idk about android but it occurs to me on **web**

**Comment by MajedDH** [comment]
It occurs to me on web too 
Shouldn't we open a new issue for it ?

**Comment by jonasbark** [comment]
Yeah I think that's a good idea

**Comment by naiteon** [comment]
> It occurs to me on web too
> Shouldn't we open a new issue for it ?

Good idea, even though there is a fix (server side) the library should be 100% http 1.1 compatible and support chucked responses.

**Comment by woprandi** [comment]
As I said here https://github.com/flutterchina/dio/issues/1077 I have this issue but I don't see any request launched from the browser
