### ISSUE TITLE
DioError [DioErrorType.response]: Http status error [403]

### ISSUE THREAD

**Issue by RahulSharma-ji** [flutterchina/dio#1166]
**CODE**
 await _dio.download(
        urlPath,
        '${dir.path}/Download/$filename.mkv}',
        cancelToken: _cancel,
        onReceiveProgress: (count, total) {
          progress = ((count / total) * 100).toInt();
          filesize = total ~/ 1024;
          downlaodResponse(progress, filesize);
        },
      );
    } catch (e) {
      print(e);
    }

**ERROR**
url :-https://eduid01-my.sharepoint.com/personal/mi_eduid01_onmicrosoft_com/_layouts/15/download.aspx?UniqueId=aab222da-9e79-4389-bc27-5a90e4bd2823

I/flutter ( 5002): DioError [DioErrorType.response]: Http status error [403]
I/flutter ( 5002): #0      DioMixin.assureDioError
package:dio/src/dio_mixin.dart:819
I/flutter ( 5002): #1      DioMixin._dispatchRequest
package:dio/src/dio_mixin.dart:678
I/flutter ( 5002): <asynchronous suspension>
I/flutter ( 5002): #2      DioMixin.fetch.<anonymous closure>.<anonymous closure> (package:dio/src/dio_mixin.dart)
package:dio/src/dio_mixin.dart:1

**Comment by mahesh1431729** [comment]
I am too getting this issue

**Comment by mahesh1431729** [comment]
please reopen the issue

**Comment by Dustlayer** [comment]
I'm getting the same error when trying to download a file via the download function.
I'm using it with Flutter Linux, but the code is the same for Android etc. (dio_for_native)
The error is fixed for me as soon as I comment this line with cancelToken in dio_for_native.dart:
```
response = await request<ResponseBody>(
        urlPath,
        data: data,
        options: options,
        queryParameters: queryParameters,
        // cancelToken: cancelToken ?? CancelToken(),
      );
```
This call is in the implementations of the download functions.

I guess the http call / stream can not be cancelled after doing this.
But otherwise the HTTP 403 is not letting me download files.
Maybe it's server specific, but for me this workaround works.

Maybe I don't understand enough, but the expression `cancelToken ?? CancelToken()` doesn't make much sense anyway, since we don't have a reference to this cancelToken then right? Shouldn't we do something like
```
cancelToken = cancelToken ?? CancelToken();
[...]
request(..., cancelToken: cancelToken, ...)
```
So we have a reference to the token?
