### ISSUE TITLE
can't post list of array

### ISSUE THREAD

**Issue by shinewanna** [flutterchina/dio#1179]
### New Issue Checklist
I try to post string list with dio. It works with lower version of dio, after upgrade to latest version of dio. I sent list of array and dio post only the last element of the array

```dart
    Dio dio = Dio();

    var map = {
      'uid': ob.uid,
      'purpose': ob.purpose,
      'facilities':  ["8", "7", "5"],
    };

//facilities is list of array contain some ids.
//when i post the map, it only post the last element, in this case "5"

   getHeader().then((header) async {
      FormData fd = FormData.fromMap(map);

      dio.options.baseUrl = BASE_URL;
      dio.options.headers = header;

      dio.post(ADDPROPERTY_END_URL, data: fd);
    });

```

### Issue Info

| Info                           | Value                                                 |      |
| ------------------------------ | ----------------------------------------------------- | ---- |
| Platform Name                  | e.g. flutter  / android                          |      |                          |      |
| Dio Version                    | e.g.  ^4.0.0                           |      |
| Android Studio / Xcode Version | e.g. Android Studio 3.3.2             |      |

### Issue Description and Steps

just try to post list of array [1, 2, 3].

**Comment by SushilGhorasaini1** [comment]
falling back to v3.0.10 solved the problem for now

**Comment by shinewanna** [comment]
if fall to v3.0.10, it's conflict other package version dependencies. 
Package creator should fix this error asap.

**Comment by nigel-gopez** [comment]
https://github.com/flutterchina/dio/issues/1155#issuecomment-842492719

**Comment by shinewanna** [comment]
Vgg

**Comment by Ruslanbek0809** [comment]
I know it is too late but this worked for me:

Step 1. Create a model for it using [json_serializable](https://pub.dev/packages/json_serializable) package by making your model `explicitToJson` to `true` as it explained here in [official flutter docs](https://docs.flutter.dev/development/data-and-backend/json#consuming-json_serializable-models) . 
Step 2. And when you want to post your generated model, don't use `formData`  in `data` property. Because `data` property is dynamic you can instead wrap your generated model with `jsonEncode` like this `data: jsonEncode(yourModel));`. In real API it should look like this: `await dio.post(api/order/', data: jsonEncode(yourModel));`

**Comment by abdalazeez1** [comment]
when i encode list like this 
 data['json_key'] = json.encode(listOfInt);///or something  else String .....
now can send list 
MapEntry(json_key: [1])

**Comment by i-zanis** [comment]
Hello I am currently having this issue too. It only posts the first item in the list.
