### ISSUE TITLE
Auth Bypass in Dart SDK when handling cross origin redirect

### ISSUE THREAD

**Issue by SunlightBro** [flutterchina/dio#1410]
### Is version 3.0.10 of Dio affected by this Dart vulnerability?
https://github.com/dart-lang/sdk/security/advisories/GHSA-c8mh-jj22-xg5h

For `dio: 4.0.0`+ this doesn't matter, as upgrading to `flutter 2.10.0` is enough.
But for old project that haven't yet upgraded to null-safety and therefor still use `dio: 3.0.10`, are they affected?

Because Dio uses the `HttpClient()` in it's [io_adapter.dart](https://github.com/flutterchina/dio/blob/da7171fa479f30bb3237c6bc1e1b35e060c2e44e/dio/lib/src/adapters/io_adapter.dart)

The google team suggests the following Workaround
```dart
final client = HttpClient();
var uri = Uri.parse('http://localhost/');
var request = await client.getUrl(uri);
request.followRedirects = false;
var response = await request.close();
while (response.isRedirect) {
  await response.drain();
  final location = response.headers.value(HttpHeaders.locationHeader);
  if (location != null) {
    uri = uri.resolve(location);
    request = await client.getUrl(uri);

    // Set the body or headers as desired.
    request.followRedirects = false;
    response = await request.close();
  }
}
```

**Comment by kuhnroyal** [comment]
Since Dio uses the `HttpClient` is probably affected in all instances where Dart <= 2.16 is used.

The same workaround applies for Dio.
Setting `BaseOptions.followRedirects = false` will prevent all requests from performing redirects.
When a redirect is needed/expected, you should perform it manually by checking `ResponseOptions.isRedirect` and then parse the redirect location in the same way as above.
