### ISSUE TITLE
Post array of Objects

### ISSUE THREAD

**Issue by retuner87** [flutterchina/dio#298]
### New Issue Checklist

- [x ] I have searched for a similar issue in the [project](https://github.com/flutterchina/dio/issues) and found none

### Issue Info

| Info                           | Value                                                 |      |
| ------------------------------ | ----------------------------------------------------- | ---- |
| Platform Name                  | e.g. flutter                          |      |
| Dio Version                    | e.g.  1.0.13                                  |      |
### Issue Description and Steps

Hi all, I'm new in Flutter and I have to send an object with an array inside, but I can't create it with FormData.

**Object to send:**

```
{
    "object_1" => {
        "arrays" => [
            {"params_1"=>"value_1", "params_2"=>"value_2", "params_3"=>"value_3"},
            {"params_1"=>"value_1", "params_2"=>"value_2", "params_3"=>"value_3"}
        ],
        "params_98"=> 1111,
        "params_99"=> 2222
    }
}
```

**I try this but doesn't work:**

```
var object = {
    'params_1': 'value_1',
    'params_2': 'value_2',
    'params_3': 'value_3'
};

var list = List();
list.add(object);
list.add(object);

var formData = FormData.from({
    'object_1[params_98]' : 1111,
    'object_1[params_99]' : 2222,
    'object_1[arrays][]' : list
});
```

And the result of the call is:

```
{
    "object_1" => {
        "arrays" => [
            "{params_1: value_1, params_2: value_2, params_3: value_3}",
            "{params_1: value_1, params_2: value_2, params_3: value_3}"
        ]
        "params_98" => "1111",
        "params_99" => "2222"
    }
}
```

How can i fix/do it?

**Comment by retuner87** [comment]
I find the solution: not use FormData, but classic json object structure:

`var items = [];
var item = {
    "params_1": value_1,
    "params_2": value_2,
    "params_3": value_3
};

items.add(item);
items.add(item);

// create params
var params = {
    "object_1": {
        "arrays": items,
        "params_98": "1111",
        "params_99": "2222"
    }
};`

and use 

`response = await dio.post("/endPoint", data: params);`

**Comment by shinewanna** [comment]
it's dosen't work for me
<img width="564" alt="Screen Shot 2020-02-07 at 10 43 32 AM" src="https://user-images.githubusercontent.com/39454969/74002007-11c3ec80-499c-11ea-9896-91be3e821a16.png">

**Comment by Ruslanbek0809** [comment]
I know it is too late but this worked for me:

Step 1. Create a model for it using [json_serializable](https://pub.dev/packages/json_serializable) package by making your model `explicitToJson` to `true` as it explained here in [official flutter docs](https://docs.flutter.dev/development/data-and-backend/json#consuming-json_serializable-models) . 
Step 2. And when you want to post your generated model, don't use `formData`  in `data` property. Because `data` property is dynamic you can instead wrap your generated model with `jsonEncode` like this `data: jsonEncode(yourModel));`. In real API it should look like this: `await dio.post(api/order/', data: jsonEncode(yourModel));`
