### ISSUE TITLE
About the validity of baseurl

### ISSUE THREAD

**Issue by FingerArt** [flutterchina/dio#385]
When I use the following code:

```dart
var dio = Dio(BaseOptions(
  baseUrl: "http:domain/api/v1"
));

dio.get("users", options: RequestOptions(baseUrl: "http:domain/api/v2"));
```
Finally, `http:domain/api/v1` is in effect, I hope `http:domain/api/v2` has a higher priority.

**Comment by emakar** [comment]
Well, as per latest dio
```
dio.get("users", options: RequestOptions(baseUrl: "http:domain/api/v2"));
```
won't compile
neither do `options: BaseOptions` as it can't be assigned

**Comment by emakar** [comment]
As I see it's only possible to set `Options` now, and there is no way to override `baseUrl` for single request anymore

**Comment by HadiHassan22** [comment]
I have a usecase where the baseurl has different subdomains depending on which workspace the user is signed in to.

for example: 
auth.example.com
myworkspace1.example.com
myworkspace2.example.com

Preferably i wanna have only one instance of dio since I wanna be able to listen from the repository layer to sign out the user on a 401 http error therefore I need to be able to change the base url dynamically on the shared instance of the dio object

**Comment by ariefwijaya** [comment]
Any update on this?

**Comment by haoyuant** [comment]
Having the same issue, would like to overwrite the base URL for only one request, couldn't find a way to do it.

**Comment by ariefwijaya** [comment]
Here is the simple implementation that could work. I'm using this and it works as expected.
```
 String _pathUrl =
          overrideBaseUrl != null ? (overrideBaseUrl + pathUrl) : pathUrl;
      final response = await dio.get(_pathUrl,
          queryParameters: body, options: Options(headers: headers));
```
When we are using full url with its protocol + domain, dio will use that new base url

**Comment by Alvish0407** [comment]
You can even create whole new instance of the Dio(). Specifying new baseUrl.
