### ISSUE TITLE
what is the latest version??

### ISSUE THREAD

**Issue by juyao** [flutterchina/dio#39]
I try to get the 0.0.10,but I cannot get it??where can  I find the latest version for Dio??thanks

**Comment by wendux** [comment]
There are two ways to learn what's the latest version:
1.  From pub: https://pub.dartlang.org/packages/dio
2. From the doc:
   
![image](https://user-images.githubusercontent.com/20411648/43186648-e3ec8c66-9021-11e8-9e63-9702d87dac12.png)

**Comment by juyao** [comment]
thank you!!

**Comment by juyao** [comment]
I have another question, if I have many request at the same time,need I new many dio objects? or ,one object can do many requests at the same time?

**Comment by wendux** [comment]
Yes! one instance can do many requests. Most of time, you just need to create one instance to perform all requests. Only When you need different default config for different requests, you should create different instances, because different instance with different default config(`Options`) that you can set。

**Comment by juyao** [comment]
OK,I know, thank you very much!

**Comment by juyao** [comment]
when I change the version to the latest version 0.1.7, I receieved the below error:

**Comment by zll33** [comment]
Hi I have a same problem as @yuyao comment.
when I updated dio version in pubspec.yaml file as 'dio: ^0.1.7'
Some error happened

/Flutter/flutter/bin/flutter --no-color packages get
Running "flutter packages get" in monitoring...
Because monitoring depends on dio ^0.1.7 which doesn't match any versions, version solving failed.
pub get failed (1)
Process finished with exit code 1

Could someone help me ? thank you.

**Comment by wendux** [comment]
@juyao @zll33 Please try again !  I have succeed just now in my box.

**Comment by tinvyhx** [comment]
depends on dio >=0.0.2 <0.1.1 which requires SDK version >=1.20.1 <2.0.0, version solving failed.

pub get failed (1)

**Comment by tinvyhx** [comment]
The current Dart SDK version is 2.1.0-dev.1.0.flutter-ccb16f7282.
