### ISSUE TITLE
请问dio是否支持flutter web  大概何时会支持

### ISSUE THREAD

**Issue by jahnli** [flutterchina/dio#448]
![image](https://user-images.githubusercontent.com/20943608/64667458-7d0c9f80-d48c-11e9-8c6c-22c873c22d7f.png)

**Comment by wendux** [comment]
Dio will support flutter web soon。

**Comment by Triipaxx** [comment]
> Dio will support flutter web soon。

is there any roadmap? when do you think flutter web is supported?

**Comment by rafaldziuryk** [comment]
Possibly dup #443

**Comment by wendux** [comment]
Done! Please update to v2.2.0 and try the new features. 
However, it should be noted that in order to support flutter web, our 2.2 is not fully compatible with 2.1.  The following documents can help you to upgrade to v2.2.0：
1. [2.2.0 change log](https://github.com/flutterchina/dio/blob/master/dio/CHANGELOG.md)
2. [从2.1升级到2.2](https://github.com/flutterchina/dio/blob/master/migration_to_2.2.x.md)

**Comment by ymback** [comment]
> Done! Please update to v2.2.0 and try the new features.
> However, it should be noted that in order to support flutter web, our 2.2 is not fully compatible with 2.1. The following documents can help you to upgrade to v2.2.0：
> 
> 1. [2.2.0 change log](https://github.com/flutterchina/dio/blob/master/dio/CHANGELOG.md)
> 2. [从2.1升级到2.2](https://github.com/flutterchina/dio/blob/master/migration_to_2.2.x.md)

I think this should be 3.0.0

PS:说好的一周就一周，有理有据，使人性福

**Comment by wendux** [comment]
@ymback Right you are! change version to 3.0.0
