### ISSUE TITLE
在flutter web中如何设置proxy

### ISSUE THREAD

**Issue by philos3** [flutterchina/dio#524]
### New Issue Checklist
在flutter web中如何设置proxy？

按照例子
```
 var dio = Dio();
  // dio.options.connectTimeout = 2000;
  // More about HttpClient proxy topic please refer to Dart SDK doc.
  (dio.httpClientAdapter as DefaultHttpClientAdapter).onHttpClientCreate =
      (HttpClient client) {
    client.findProxy = (uri) {
      //proxy all request to localhost:8888
      return "PROXY localhost:8888";
    };
    client.badCertificateCallback =
        (X509Certificate cert, String host, int port) => true;
  };
  var dir = Directory("./cookies");
  await dir.create();
  Response<String> response;
  //response= await dio.get("https://github.com/wendux/fly");
  response = await dio.get("https://www.baidu.com");
  print(response.statusCode);
  response = await dio.get("https://www.baidu.com");
  print(response.statusCode);
```

### Issue Info

报错信息：Expected a value of type 'DefaultHttpClientAdapter', but got one of type 'BrowserHttpClientAdapter'

**Comment by xiyulangzi** [comment]
import 'package:dio/adapter.dart';

**Comment by philos3** [comment]
> import 'package:dio/adapter.dart';

_dio.httpClientAdapter as DefaultHttpClientAdapter
这个httpClientAdapter  在web默认是BrowserHttpClientAdapter实现，但是BrowserHttpClientAdapter没有onHttpClientCreate等，如何写？引入这个包然后呢？

**Comment by xiyulangzi** [comment]
var dio = new Dio();
      (dio.httpClientAdapter as DefaultHttpClientAdapter).onHttpClientCreate = (HttpClient client) {
        client.findProxy = (uri) { return "PROXY 1.2.3.4:8080";};

        client.badCertificateCallback =
          (X509Certificate cert, String host, int port) => true;
      };

      Response response = await dio.post(
        "url....................",
        data: postBody,
        );
      print(response.data);


this code works for me.

**Comment by philos3** [comment]
> ```
>   var dio = new Dio();
>   (dio.httpClientAdapter as DefaultHttpClientAdapter).onHttpClientCreate = (HttpClient client) {
>     client.findProxy = (uri) { return "PROXY 1.2.3.4:8080";};
> 
>     client.badCertificateCallback =
>       (X509Certificate cert, String host, int port) => true;
>   };
> 
>   Response response = await dio.post(
>     "url....................",
>     data: postBody,
>     );
>   print(response.data);
> ```
> 
> this code works for me.
are you sure it's a flutter web project?  this code  works well in flutter ios /android  project but web

**Comment by Virendra-Varma** [comment]
Hi @philos3, how did you solved this issue?

**Comment by Virendra-Varma** [comment]
this problem is get solved by
`dio.httpClientAdapter = DefaultHttpClientAdapter();` adding this line but after that getting another issues
`*** DioError ***:
js_primitives.dart:32 uri: https://www.neoint.ai/NeointIdentityService/identity/connect/token
js_primitives.dart:32 DioError [DioErrorType.DEFAULT]: Unsupported operation: Platform._version
package:build_web_compilers/src/dev_compiler/C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 196:49  throw_
package:build_web_compilers/src/dev_compiler/C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/_internal/js_dev_runtime/patch/io_patch.dart 286:5               _version
package:build_web_compilers/src/dev_compiler/C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/io/platform_impl.dart 123:32                                     get version
package:build_web_compilers/src/dev_compiler/C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/io/platform.dart 76:37                                           get _version
package:build_web_compilers/src/dev_compiler/C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/utils.dart 77:6     get
package:build_web_compilers/src/dev_compiler/C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/io/platform.dart 233:32                                          get version
package:build_web_compilers/src/dev_compiler/C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/_http/http_impl.dart 3334:26                                     _getHttpVersion
package:build_web_compilers/src/dev_compiler/C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/_http/http_impl.dart 2150:22                                     new
package:build_web_compilers/src/dev_compiler/C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/_http/http.dart 1491:18                                          new
package:dio/src/adapters/io_adapter.dart 119:28                                                                                                                         [_configHttpClient]
package:dio/src/adapters/io_adapter.dart 34:23                                                                                                                          fetch
package:build_web_compilers/src/dev_compiler/C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 86:54            runBody
package:build_web_compilers/src/dev_compiler/C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 125:12           _async
package:dio/src/adapters/io_adapter.dart 25:29                                                                                                                          fetch
package:dio/src/dio.dart 919:46                                                                                                                                         _dispatchRequest
package:build_web_compilers/src/dev_compiler/C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 47:50            onValue
package:build_web_compilers/src/dev_compiler/C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/async/zone.dart 1381:54                                          runUnary
package:build_web_compilers/src/dev_compiler/C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/async/future_impl.dart 140:18                                    handleValue
package:build_web_compilers/src/dev_compiler/C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/async/future_impl.dart 682:44                                    handleValueCallback
package:build_web_compilers/src/dev_compiler/C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/async/future_impl.dart 711:32                                    _propagateToListeners
package:build_web_compilers/src/dev_compiler/C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/async/future_impl.dart 526:5                                     [_completeWithValue]
package:build_web_compilers/src/dev_compiler/C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/async/future_impl.dart 556:7                                     callback
package:build_web_compilers/src/dev_compiler/C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/async/schedule_microtask.dart 43:11                              _microtaskLoop
package:build_web_compilers/src/dev_compiler/C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/async/schedule_microtask.dart 52:5                               _startMicrotaskLoop
package:build_web_compilers/src/dev_compiler/C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 168:15           <fn>`

**Comment by catherinezhxj** [comment]
最后你如何解决了呢？

> > import 'package:dio/adapter.dart';
> 
> _dio.httpClientAdapter as DefaultHttpClientAdapter
> 这个httpClientAdapter 在web默认是BrowserHttpClientAdapter实现，但是BrowserHttpClientAdapter没有onHttpClientCreate等，如何写？引入这个包然后呢？

**Comment by philos3** [comment]
@catherinezhxj  @Virendra-Varma 

///dio_adapter_lib.dart
export 'dio_adapter_stub.dart' // Stub implementation
  if (dart.library.io) 'dio_adapter_native.dart' // dart:io implementation
  if (dart.library.html) 'dio_adapter_web.dart'; // dart:html implementation

///dio_adapter_stub.dart
import 'package:dio/dio.dart';
HttpClientAdapter getAdapter() => throw UnsupportedError('Cannot implement adapter');

///dio_adapter_native.dart
import 'package:dio/adapter.dart';
import 'package:dio/dio.dart';
HttpClientAdapter getAdapter() => DefaultHttpClientAdapter();

///dio_adapter_web.dart
import 'package:dio/adapter_browser.dart';
import 'package:dio/dio.dart';
HttpClientAdapter getAdapter() => BrowserHttpClientAdapter();
