### ISSUE TITLE
Too much memory allocation when using non stream responses

### ISSUE THREAD

**Issue by llooz** [flutterchina/dio#578]
The default response transformer reads all the stream in a `List<int>` thus allocating memory for 8 times greater than needed.
https://github.com/flutterchina/dio/blob/fdf38275092c1f55f123380e4bfb4415893edf71/dio/lib/src/transformer.dart#L91

It should use a growing `Uint8List`,  maybe with the help of a `ByteConversionSink`

**Comment by wendux** [comment]
8 times? why?

**Comment by llooz** [comment]
> 8 times? why?

Because a int is 8 byte (64 bit) while a uint8 is 1 byte (8 bit).

Note: i'm using Dio on Flutter

**Comment by wendux** [comment]
Oh... Could you please commit a PR for this problem?

**Comment by Endebert** [comment]
@wendux We ran into the same issue that @llooz is describing. Since this was a critical blocker for our app, I went ahead and tried to optimize the code based on @llooz suggestions, see here: #639 

To our use case: We tried to download & parse a JSON object that was ~5mb gzipped, then ~75mb raw. Dio during download tried to allocate much more memory, which resulted in `Out of Memory` errors. This lead to infinite retries or hard crashes.

My changes get rid of the Out of Memory errors and might also have increased performance a bit.

Could you please reopen this issue and look into the PR so that it can be integrated ASAP? Let me know if you need more information.

**Comment by sayhicoelho** [comment]
Here facing the same issue using streams.

![image](https://user-images.githubusercontent.com/8188365/84578771-99809400-ad9e-11ea-950b-e7248e559e1b.png)

My code:

```dart
static Future<Response> upload<T>(
  String url,
  Future<Uint8List> file,
  String fileName,
  {
    String imageType = 'jpeg',
    Map data = const {},
    void Function(int, int) onSendProgress,
  }
) async {
  var fileStream = file.asStream().asBroadcastStream();
  var fileBytes = (await fileStream.toList())[0];
  var fileSize = fileBytes.length;

  var formData = FormData.fromMap({
    ...data,
    'file': MultipartFile(
      Stream.fromIterable(fileBytes.map((e) => [e])),
      fileSize,
      filename: fileName,
      contentType: MediaType('image', imageType)
    ),
  });

  var options = Options(
    headers: {
      Headers.contentLengthHeader: formData.length,
    }
  );

  return _dio.post<T>(
    url,
    data: formData,
    options: options,
    onSendProgress: onSendProgress,
  );
}
```

**Comment by Endebert** [comment]
I can see:

1. `Future<Uint8List> file,`: when this fulfills, you have the whole file in memory
2. `var fileStream = file.asStream().asBroadcastStream();`: wouldn't this create a stream with only one event (that is when the future `file` fulfills?)
3. `var fileBytes = (await fileStream.toList())[0];`: I believe here you're creating another copy of the file into memory
4. `Stream.fromIterable(fileBytes.map((e) => [e]))`: So here you are creating a new stream event for every byte of the file, and encapsulate that in a new array each time. This might be the main cause for the memory overhead.

Simple fix would be that for (4), you write instead `Stream.fromIterable([fileBytes])`.

Since you're getting the whole file as a Future anyways, try to use `MultipartFile.fromBytes` instead. Check the docs here: https://github.com/flutterchina/dio/blob/master/dio/lib/src/multipart_file.dart#L34-L36

>   /// Creates a new [MultipartFile] from a chunked [Stream] of bytes. The length
  /// of the file in bytes must be known in advance. If it's not, read the data
  /// from the stream and use [MultipartFile.fromBytes] instead.

Which seems to do the same as the simple fix I suggested: https://github.com/flutterchina/dio/blob/master/dio/lib/src/multipart_file.dart#L57

---

To keep it clean, I'd suggest a solution like this:

```dart
static Future<Response> upload<T>(
  String url,
  Future<Uint8List> file,
  String fileName,
  {
    String imageType = 'jpeg',
    Map data = const {},
    void Function(int, int) onSendProgress,
  }
) async {
  var formData = FormData.fromMap({
    ...data,
    'file': MultipartFile.fromBytes(
      await file,
      filename: fileName,
      contentType: MediaType('image', imageType)
    ),
  });

  var options = Options(
    headers: {
      Headers.contentLengthHeader: formData.length,
    }
  );

  return _dio.post<T>(
    url,
    data: formData,
    options: options,
    onSendProgress: onSendProgress,
  );
}
```

**Comment by sayhicoelho** [comment]
Thanks for the feedback @Endebert.

I've used fromBytes before, but can't get upload progress properly.

Please see this comment: https://github.com/dart-lang/sdk/issues/35427#issuecomment-638017983
And this: https://github.com/dart-lang/sdk/issues/35427#issuecomment-643632564
And this issue: https://github.com/flutterchina/dio/issues/801

Why this happens when using fromBytes?

I just fixed the issue using MultipartFile.fromFile. When I take de picture using camera, I need to store the file in a temp folder to do the upload and then remove that file.
