### ISSUE TITLE
As my app in background,the dio will show some error

### ISSUE THREAD

**Issue by beydeng** [flutterchina/dio#620]
like
I/flutter (12431): content{"errorMsg":"DioError [DioErrorType.DEFAULT]: SocketException: Failed host lookup: 'cloud-services.xiaoban.mobi' (OS Error: No address associated with hostname, errno = 7)","errorCode":1}

or 

I/flutter (10728): content{"errorMsg":"DioError [DioErrorType.CONNECT_TIMEOUT]: Connecting timed out

**Comment by brianb-sf** [comment]
I see something similar as well. In my investigation, it seems like when the application enters the background at the correct time I see `DioError [DioErrorType.CONNECT_TIMEOUT]`. I have had a hard time tracking down the root cause of why these errors occur.

Do requests need to be canceled when the application enters the background maybe?

**Comment by ITAnt** [comment]
Why closed this bug? This is still happening in the lastest version. Just let me down.

**Comment by catmaomao** [comment]
i have the same issue.DioError [DioErrorType.CONNECT_TIMEOUT] when app in background

**Comment by himanshu447** [comment]
This issue still exists for IOS

**Comment by daniel-py** [comment]
this issue still exists for IOS (Not too sure about android). Any solution please??

**Comment by duytq94** [comment]
Same error for both ios & android
