### ISSUE TITLE
Web: freeze UI

### ISSUE THREAD

**Issue by Gorniv** [flutterchina/dio#666]
### New Issue Checklist

- [x] I have searched for a similar issue in the [project](https://github.com/flutterchina/dio/issues) and found none

### Issue Info

| Info                           | Value                                                 |      |
| ------------------------------ | ----------------------------------------------------- | ---- |
| Platform Name                  | web                          |      |
| Platform Version               |                                |      |
| Dio Version                    | 3.0.8                                  |      |
| Repro rate                     | 100%   |      |
| Repro with our demo prj        |            |      |
| Demo project link              |   |      |

### Issue Description and Steps

When I dio.get big JSON file (2-5 Mb) - I have freeze UI on the Web about 10-30 seconds. Standard HttpClient work fine.

**Comment by softmarshmallow** [comment]
mine freezes about 300 ms. which is still laggy since i call api call every 2 seconds.

**Comment by ganigeorgiev** [comment]
I encountered the same problem with 1MB+ json response.

I believe it is because the response is fetched as blob ([browser_adapter#L31](https://github.com/flutterchina/dio/blob/master/dio/lib/src/adapters/browser_adapter.dart#L31)) and a [stream is created from it](https://github.com/flutterchina/dio/blob/632931586b5153fb03f58a75378e59b564276b82/dio/lib/src/adapter.dart#L99) (the actual slow part is consuming the stream).

**Comment by Gorniv** [comment]
up

**Comment by 100cm** [comment]
same behaviro on ios .any solution?

**Comment by Manguelo** [comment]
Same for me on web

**Comment by marukami** [comment]
I had a freeze on a 246kb JSON for ~4-6sec. Running the CPU sampler in Chrome shows there is a lot of GC coming from `List_List$from` inside `ResponseBody.fromBytes`. This seems to be what `Uint8List.fromList` is been called in JS and we are invoking it for each byte. https://github.com/flutterchina/dio/blob/632931586b5153fb03f58a75378e59b564276b82/dio/lib/src/adapter.dart#L99-L100

Here is a sample of the CPU sampler from Chrome.
![image](https://user-images.githubusercontent.com/1644094/85947601-17dc5900-b98f-11ea-8d46-1ae17be56f40.png)

So I swapped it out with `Stream.value(Uint8List.fromList(bytes))` to take the whole list all at once, and all GC from before is gone; now only thing CPU Sampler seems to find is the UTF8 decode and JSON parse at ~20ms each in debug mode.

![image](https://user-images.githubusercontent.com/1644094/85947614-2dea1980-b98f-11ea-955d-1b336484e05d.png)

I used Profiler mode in Debug for all the sampling. Running in release mode did not seem to affect the GC much. Also `Stream.value` requires Dart 2.5, but, we can fall back to `Future.value(Uint8List.fromList(bytes)).asStream()` for the current min Dio Dart version.

**Comment by softmarshmallow** [comment]
reopen

**Comment by urusai88** [comment]
reopen pls, problem is not gone

**Comment by LucaIaconelli** [comment]
Can anyone help me on this?

**Comment by urusai88** [comment]
> Can anyone help me on this?
you can try this
https://github.com/urusai88/dio/tree/feature/refactor-progress

**Comment by LucaIaconelli** [comment]
Thanks, I'll

**Comment by Oualitsen** [comment]
Hello Guys,
I think the problem comes from the `BrowserHttpClientAdapter` from dio.
After hours of manual profiling (the old way) I found out that the operation that take a lot of time is 
`if (requestStream == null) {
      xhr.send();
    } else {
     //The killer is the reduce method used here.
      requestStream
          .reduce((a, b) => Uint8List.fromList([...a, ...b]))
          .then(xhr.send);
    }`

I copied this class and changed the reduce method with regular for loop and it works pretty fast for me.

`if (requestStream == null) {
      xhr.send();
    } else {
      List<int> r = [];
      List<List<int>> listOfLists = await requestStream.toList();
      for (int i = 0; i < listOfLists.length; i++) {
        r.addAll(listOfLists[i]);
      }
      xhr.send(Uint8List.fromList(r));
    }`

Here is the full `WebAdapter `class that I am using (for web only) instread of the default `BrowserHttpClientAdapter`

`import 'dart:async';
import 'dart:typed_data';
import 'package:dio/dio.dart';
import 'dart:html';

class WebClientAdapter implements HttpClientAdapter {
  /// These are aborted if the client is closed.
  final _xhrs = <HttpRequest>[];

  /// Whether to send credentials such as cookies or authorization headers for
  /// cross-site requests.
  ///
  /// Defaults to `false`.
  ///
  /// You can also override this value in Options.extra['withCredentials'] for each request
  bool withCredentials = false;

  @override
  Future<ResponseBody> fetch(RequestOptions options, Stream<List<int>> requestStream, Future cancelFuture) async {
    var xhr = HttpRequest();
    _xhrs.add(xhr);

    xhr
      ..open(options.method, options.uri.toString(), async: true)
      ..responseType = 'blob'
      ..withCredentials = options.extra['withCredentials'] ?? withCredentials;
    options.headers.remove(Headers.contentLengthHeader);
    options.headers.forEach((key, v) => xhr.setRequestHeader(key, '$v'));
    var completer = Completer<ResponseBody>();

    xhr.onLoad.first.then((_) {
      // TODO: Set the response type to "arraybuffer" when issue 18542 is fixed.
      var blob = xhr.response ?? Blob([]);
      var reader = FileReader();

      reader.onLoad.first.then((_) {
        var body = reader.result as Uint8List;

        completer.complete(
          ResponseBody.fromBytes(
            body,
            xhr.status,
            headers: xhr.responseHeaders.map((k, v) => MapEntry(k, v.split(','))),
            statusMessage: xhr.statusText,
            isRedirect: xhr.status == 302 || xhr.status == 301,
          ),
        );
      });

      reader.onError.first.then((error) {
        completer.completeError(
          DioError(
            type: DioErrorType.RESPONSE,
            error: error,
            request: options,
          ),
          StackTrace.current,
        );
      });

      reader.readAsArrayBuffer(blob);
    });

    xhr.onError.first.then((_) {
      // Unfortunately, the underlying XMLHttpRequest API doesn't expose any
      // specific information about the error itself.
      completer.completeError(
        DioError(
          type: DioErrorType.RESPONSE,
          error: 'XMLHttpRequest error.',
          request: options,
        ),
        StackTrace.current,
      );
    });

    cancelFuture?.then((_) {
      if (xhr.readyState < 4 && xhr.readyState > 0) {
        try {
          xhr.abort();
        } catch (e) {
          // ignore
        }
      }
    });

    if (requestStream == null) {
      xhr.send();
    } else {
      List<int> r = [];
      List<List<int>> listOfLists = await requestStream.toList();
      for (int i = 0; i < listOfLists.length; i++) {
        r.addAll(listOfLists[i]);
      }
      xhr.send(Uint8List.fromList(r));
    }
    return completer.future.whenComplete(() {
      _xhrs.remove(xhr);
    });
  }

  /// Closes the client.
  ///
  /// This terminates all active requests.
  @override
  void close({bool force = false}) {
    if (force) {
      for (var xhr in _xhrs) {
        xhr.abort();
      }
    }
    _xhrs.clear();
  }
}
`
I hope it helps.
Salam.

**Comment by arthurdlima** [comment]
No fix yet.. Any updates?

**Comment by NamanShergill** [comment]
this issue still exists

**Comment by softmarshmallow** [comment]
Using flutterchina's project seems to be dangerous

**Comment by nstrelow** [comment]
I guess this is still an issue?
Is this mentioned at least in the readme somewhere?

**Comment by 86driver** [comment]
Still facing this issue too,

**Comment by Nicola-Cestaro** [comment]
Up

**Comment by jgoyvaerts** [comment]
This issue has been fixed on our fork of dio, [dio_http](https://github.com/dart-tools/dio_http).

Package is available here: https://pub.dev/packages/dio_http

**Comment by talski** [comment]
> This issue has been fixed on our fork of dio, [dio_http](https://github.com/dart-tools/dio_http).
> 
> Package is available here: https://pub.dev/packages/dio_http

Should this have fixed upload too? when I upload files > 1mb, the ui hangs until it finishes upload

**Comment by jgoyvaerts** [comment]
Still need to fix the upload part, will take a look at it soon.

**Comment by jgoyvaerts** [comment]
Upload has been fixed in 5.0.4 @talski
