### ISSUE TITLE
DioError [DioErrorType.RESPONSE]: Http status error [415]

### ISSUE THREAD

**Issue by H-Mongo** [flutterchina/dio#743]
### Issue Info
在项目中设置了contentType，但是在后端获取contentType与Content-Type时都是null，试了很多遍都不行，后端通路，就是dio提交数据过去没办法获取这两个属性。

| Info                           | Value                                                 |      |
| ------------------------------ | ----------------------------------------------------- | ---- |
| Platform Name                  | flutter /android                          |      |
| Platform Version               | 1.12.23+hotfix.8                           |      |
| Dio Version                    | 2.1.0                                |      |
| Android Studio / Xcode Version | no            |      |
| Repro rate                     | all the time (0%)   |      |
| Repro with our demo prj        |don't try           |      |
| Demo project link              | e.g. link to a demo project that highlights the issue |      |

### Issue Description and Steps
我的dio被我封装一个单例。
global config:
```dart
_dio.options = BaseOptions(
        baseUrl: API.baseUri,
        connectTimeout: 5000,
        receiveTimeout: 3000,
        contentType: Headers.jsonContentType,
        headers: {
          'Authorization': 'Bearer '
        }
```
single request config：
```dart
await BjuHttp.post(
                              API.addComment, 
                              data: data,
                              options: Options(contentType: Headers.jsonContentType, headers: {"Content-Type": "application/json"})
                            )
```
请求后后台日志：
```console
22:43:10.517 [http-nio-8080-exec-7] WARN  org.springframework.web.servlet.mvc.support.DefaultHandlerExceptionResolver - Resolved [org.springframework.web.HttpMediaTypeNotSupportedException: Content type '' not supported]
22:43:10.528 [http-nio-8080-exec-7] INFO  top.hzwei.bju.common.intercepter.JWTIntercepter - #### ContentType=null, Content-Type=null
```

**Comment by wendux** [comment]
检查一下data是否为null?

**Comment by H-Mongo** [comment]
Since I changed a method, this problem has not occurred. I feel that DIO's global BaseOptions settings cannot be overridden by options. See if other users have experienced this problem

**Comment by amercobra** [comment]
I'm getting the same error, anyone was able to resolve it?

**Comment by amercobra** [comment]
I was able to solve the issue by defining BaseOptions, exactly like the following:

`
import 'package:dio/dio.dart' as dio;


String baseUrl = 'http://YourLinkHere/api/';
  dio.BaseOptions _dioOpts = dio.BaseOptions(
    method: 'POST',
    connectTimeout: 1000000,
    sendTimeout: 100000,
    receiveTimeout: 100000,
    baseUrl: baseUrl,
    headers: {
      HttpHeaders.userAgentHeader: '*********',
      HttpHeaders.acceptCharsetHeader: 'utf-8',
      HttpHeaders.acceptEncodingHeader: 'gzip, deflate, br',
      HttpHeaders.acceptHeader: '*/*',
      HttpHeaders.acceptLanguageHeader: 'en-US',
      HttpHeaders.contentTypeHeader: 'multipart/form-data;',
      HttpHeaders.connectionHeader: 'keep-alive',
    },
    contentType: dio.Headers.jsonContentType,
    responseType: dio.ResponseType.json,
  );

//then, executing the Post Method like this:
    try {
      dio.Response response = await dio.Dio(_dioOpts).request(
        'UserPhoto',
        data: dio.FormData.fromMap(jsonData), //Getting FormData object from jsonData: Map<String, Object>
      );

      if(response.statusCode == 200)
        return 'Success';
      else
        return '';

    } catch (e) {
      print("Exception Caught: $e");
      return '';
    }

`

**Comment by ManKeomorakort** [comment]
I have the same issue after update to this version. any solution yet?

**Comment by devmaczw** [comment]
I have a similar issue on the latest version and even the previous one. It seems Dio cant handle any other response codes except 200. I have an authentication endpoint and been sending forbiden or unauthorized response code but i get an exception thown with the error  DioError [DioErrorType.RESPONSE]: Http status error [403] or  DioError [DioErrorType.RESPONSE]: Http status error [401]. I tried catching it as shown below, the exception can't be caught, it gows straight to the dio.dart file on the _dispatchRequest() method and code hanges, as shown below. Only way to go ahead was to return a 200 with a json of response etc, but thats not really ideal. Why cant it just handle the http codes and return them on the statusCode parameter like iot does 200.

Here i try to catch the exception but cannot.
![Screenshot (29)](https://user-images.githubusercontent.com/54586967/88683710-63039c00-d0f4-11ea-8b17-36b72d312e44.png)

Tried again to catch it on the auth.controller.dart file, stuill cannmot be caught
![Screenshot (32)](https://user-images.githubusercontent.com/54586967/88684190-ddccb700-d0f4-11ea-9a27-0f469365205d.png)

I see this issue was opened on April 15, still not fixed yet? Any solution to this, or maybe I wrote my code wrong.

**Comment by devmaczw** [comment]
Should i open a new issue for y'all guys to work on it?

**Comment by titopalito** [comment]
To me the solution was set the contentType header like this:

```
Dio dio = new Dio();
dio.options.contentType = Headers.formUrlEncodedContentType;
```
Search for your type of content.

Best regards

**Comment by SongLinYang12138** [comment]
我是这样解决的，需要设置拦截器  dio: ^4.0.0  
var baseUrl="";
BaseOptions _dioOpts = BaseOptions(
      method: 'POST',
      connectTimeout: 1000000,
      sendTimeout: 100000,
      receiveTimeout: 100000,
      baseUrl: baseUrl,
      contentType: Headers.formUrlEncodedContentType,
      responseType: ResponseType.json,
    );

  Interceptor interceptor = LogInterceptor(
      requestHeader: true,
      requestBody: true,
      responseBody: true,
      responseHeader: false,
      error: true,
    );
      Dio dio = Dio(_dioOpts);
      dio.interceptors.add(interceptor);
