### ISSUE TITLE
下载任务使用 cancelToken cancel以后，再次使用dio发请求，所有的请求都发不成功

### ISSUE THREAD

**Issue by wenlei1990** [flutterchina/dio#752]
报错  : Bad state: Client is closed

flutter sdk 1.12.13

dio版本: 3.0.9

**Comment by LsFern** [comment]
我也遇到了这个问题。程序请求使用同一个token的时候

**Comment by qcdys** [comment]
> 报错：状态错误：客户已关闭
> 
> 颤振SDK 1.12.13
> 
> dio版本：3.0.9



> 我也遇到了这个问题。程序请求使用同一个令牌的时候
两位怎么解决的

**Comment by qcdys** [comment]
> 报错：状态错误：客户已关闭
> 
> 颤振SDK 1.12.13
> 
> dio版本：3.0.9



> 我也遇到了这个问题。程序请求使用同一个令牌的时候




两位大佬怎么解决的，能分享一下吗

**Comment by LsFern** [comment]
只能每个请求设置自己独有的canceltoken




            
            
                
                    
                            
                                
                            
                            
                                fighting_android
                            
                    
                        
                            
                                    邮箱：fighting_android@sina.com
                            
                        
                
            
        Signature is customized by Netease Mail Master


在2020年08月04日 10:39，vue2-template 写道： 

报错：状态错误：客户已关闭
颤振SDK 1.12.13
dio版本：3.0.9


我也遇到了这个问题。程序请求使用同一个令牌的时候

两位大佬怎么解决的，能分享一下吗

—You are receiving this because you commented.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/flutterchina/dio/issues/752#issuecomment-668346531",
"url": "https://github.com/flutterchina/dio/issues/752#issuecomment-668346531",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]
