### ISSUE TITLE
Use try/catch instead of catchError

### ISSUE THREAD

**Issue by themightychris** [flutterchina/dio#887]
See Dart-Code/Dart-Code#2701 and dart-lang/linter#2212

**Comment by themightychris** [comment]
this is still an issue

**Comment by jmealo** [comment]
This is still an issue.

**Comment by ryon** [comment]
Still an issue

**Comment by themightychris** [comment]
not stale, still driving flutter devs nuts on the daily

**Comment by ryon** [comment]
Yes, this is still an issue

**Comment by jmealo** [comment]
Yes, this is still still an issue.

**Comment by themightychris** [comment]
common stalebot

**Comment by HE-LU** [comment]
This is still and issue!

**Comment by AlexV525** [comment]
@DanTup Are the mentioned issues still effective? In https://github.com/dart-lang/linter/issues/2212#issuecomment-777434208 you said the original reason has been resolved.

**Comment by DanTup** [comment]
My understanding is that the fixes in https://github.com/dart-lang/sdk/issues/37953 mean this is not necessary. When the issue was opened, the debugger did not understand that `.catchError()` was handling the exception, so the debugger would treat it as "uncaught". This is no longer the case.

There may still be some places where the debugger isn't correctly considering exceptions caught though (like https://github.com/dart-lang/sdk/issues/47985) so this fix doesn't necessarily mean all related issues are solved (but those that still exist should have issues raised with clear example code to repro).
